webtalk_init -webtalk_dir F:\\digilent\\WAFBP\\Walking_assistant_for_blind_people_v1\\WAFBP\\WAFBP.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-05-04 22:44:21" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211690469_0_0_444" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc1rrq68obnrkos2ak1v8bohio" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.355 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1556996152316" -context "sdk\\\\bsp/1556996152316"
webtalk_add_data -client sdk -key hwid -value "1554150566565" -context "sdk\\\\bsp/1556996152316"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1556996152316"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1556996152316"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1556996152316"
webtalk_add_data -client sdk -key uid -value "1556996188115" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key hwid -value "1554150566565" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key bspid -value "1556996152316" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key projSize -value "594.8359375" -context "sdk\\\\application/1556996188115"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key BootgenCount -value "2" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1556999061558"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1556999061558"
webtalk_transmit -clientid 1259680228 -regid "211690469_0_0_444" -xml F:\\digilent\\WAFBP\\Walking_assistant_for_blind_people_v1\\WAFBP\\WAFBP.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\digilent\\WAFBP\\Walking_assistant_for_blind_people_v1\\WAFBP\\WAFBP.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\digilent\\WAFBP\\Walking_assistant_for_blind_people_v1\\WAFBP\\WAFBP.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
