# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/digilent/WAFBP/Walking_assistant_for_blind_people_v1/WAFBP/WAFBP.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
